### ISSUE TITLE
🐛 Fast typing results into losing chars

### ISSUE THREAD

**Issue by Amzoobalance** [ordo-pink/ordo-electron#132]
When typing very quickly (basically, rolling over the keyboard) some characters are lost but the caret position is updated properly. This leads to losing caret visually.

**Comment by orlowdev** [comment]
My suggestion is to try including caret positions and raw string value into the parsed file object stored in the state of the editor component. Probably this way it would make the component rerender properly.

**Comment by orlowdev** [comment]
Obsolete after client extraction
