### ISSUE TITLE
✨ Add a wizard for new users

### ISSUE THREAD

**Issue by aleksandr-konovalov** [ordo-pink/ordo-electron#144]
### What is it you truly desire

Add a wizard for new users

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by orlowdev** [comment]
I'll take this one. The plan is:

- We check if the user starts the app for the first time
- We open introduction wizard that will allow picking the language and the directory to store user content
- We create a set of files that teach the user the basics of how to work with Ordo

**Comment by orlowdev** [comment]
Should include a fix for #59
