### ISSUE TITLE
✨ Add icons to create files and folders

### ISSUE THREAD

**Issue by aleksandr-konovalov** [ordo-pink/ordo-electron#145]
### What is it you truly desire

Add icons to create files and folders

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by orlowdev** [comment]
Any ideas on where to put those buttons?

BTW, after #147 is merged, file and folder creation will be available with three scenarios:

- **Ctrl/Cmd + Shift + P** -> Create file (or, Create directory)
- **Ctrl/Cmd + N** -> Create file; **Ctrl/Cmd + Shift + N** -> Create directory
- Right click on a folder or the file explorer -> Create file (or, Create directory)
