### ISSUE TITLE
🐛 Fix collision of interface elements in Mac OS

### ISSUE THREAD

**Issue by aleksandr-konovalov** [ordo-pink/ordo-electron#146]
### What happened?

A bug happened!Fix collision of interface elements in Mac OS

### Version

0.1.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by orlowdev** [comment]
This one is pretty straightforward: go to `src/main/index.ts` and replace the value for `titleBarStyle` with `default`. That should be it.

**Comment by orlowdev** [comment]
Reference: 

![Image](https://user-images.githubusercontent.com/13219379/197394969-70993cef-44d5-42c1-86d7-8952e47d16c8.png)
