### ISSUE TITLE
🐛 Ordo application window does not appear on Windows

### ISSUE THREAD

**Issue by orlowdev** [ordo-pink/ordo-electron#151]
### What happened?

There are three processes of Ordo in the Task Manager, but the window remains invisible.

### Version

0.2.0

### Relevant log output

```sh
Выпуск  Windows 10 Pro
Версия  21H2
Дата установки  ‎12.‎08.‎2021
Сборка ОС  19044.2130
Взаимодействие  Windows Feature Experience Pack 120.2212.4180.0
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mariameleonis** [comment]
Hi, guys! I have the same problem:(

Edition	Windows 10 Pro
Version	21H2
Installed on	‎5/‎25/‎2022
OS build	19044.2251
Experience	Windows Feature Experience Pack 120.2212.4180.0
