### ISSUE TITLE
Show spinner when opening Graph View

### ISSUE THREAD

**Issue by orlowdev** [ordo-pink/ordo-electron#28]
Graph View (the "share icon" thing in the Activity Bar) can take quite some time to load on big projects. It would be nice to have some sort of spinner at the center that will inform the user that something is happening.

**Comment by orlowdev** [comment]
https://user-images.githubusercontent.com/13219379/183383244-0eb4d856-0723-4974-a0d5-b5313a108d9c.mp4

It sparkles for a second which looks weird. Can this be fixed easily?

**Comment by orlowdev** [comment]
@tgafiulin Can you check the previous comment please? If it's a long fix, I'll merge it as is

**Comment by tgafiulin** [comment]
@orlowdev fixed)
