### ISSUE TITLE
🐛 Unable to create file/ open folder on macOS Monterey (M1)

### ISSUE THREAD

**Issue by ireshetov** [ordo-pink/ordo-electron#59]
Steps:
- downloaded the application from official site
- opened dmg 
- moved application to application folder
- warning to allow run application from untrusted developer appeared 
- allowed
- opened application 
- tried to create a file without success with error
￼
![Pasted Graphic 1](https://user-images.githubusercontent.com/4737422/186677898-542b73d4-4d1b-466f-b016-3dd77d0a07f4.jpg)

**Comment by ireshetov** [comment]
Uncaught Exception:
TypeError: Cannot read properties of null (reading 'path')
at /Applications/Ordo.app/Contents/Resources/app/.webpack/main/index.js:8:313080
at e.select (/Applications/Ordo.app/Contents/Resources/app/.webpack/main/index.js:8:328421)
at click (/Applications/Ordo.app/Contents/Resources/app/.webpack/main/index.js:8:313033)
at MenuItem.click (node:electron/js2c/browser_init:73:1908)
at EventEmitter.a._executeCommand (node:electron/js2c/browser_init:81:2453)

**Comment by orlowdev** [comment]
Thank you for the info. It seems like you tried to create a file in a folder that requires extended permissions. Neither reading nor writing is permitted there. We'll fix this by informing the user that the folder requires those permissions and request them from the OS (if we find the way, at least). Meanwhile, you can create a dedicated folder inside `/Users/ireshetov`, e.g. `/Users/ireshetov/docs` and open it with Ordo. It should work without issues. Please let me know if it does not.

**Comment by ireshetov** [comment]
Your suggestion works fine. But from my perspective, it is not clear from the first launch that I should create a folder (aka workdir).
I would suggest adding a quick tour and playing it once a user runs the app for the first time.
