### ISSUE TITLE
🔒 Remove dependency on `path` in OrdoFile and OrdoDirectory

### ISSUE THREAD

**Issue by Amzoobalance** [ordo-pink/ordo-electron#78]
Since there can only be one folder where users host their Ordo files, storing the full path does not make much sense - relative path is already unique. Using relative path on the web would be convenient as well. To make it easier on the Electron side it would be enough to have a function that simply joins `personalProjectDirectory` from the settings with the relative path of the file.

Don't forget to trim the `../` things to avoid accessing files or directories outside the scope of the personal project folder.

**Comment by orlowdev** [comment]
Relates to #59
