### ISSUE TITLE
✨ Add "Reveal in files" command

### ISSUE THREAD

**Issue by Amzoobalance** [ordo-pink/ordo-electron#82]
The `Reveal in Files` command should be available via:

- [ ] Right click menu on files, directories, and empty file explorer space

If there is a file opened in the Editor, these should work on the currently opened file. Otherwise - on the `personalProject` directory:

- [ ] Command Palette (Ctrl (Cmd on Mac) + Shift + P)
- [ ] Keyboard shortcut (Ctrl (Cmd on Mac) + Alt + R)

**Comment by Tayler89Derden** [comment]
Show file path is opened by pressing the trackpad and selecting the menu, but the hotkeys do not work on both the open file and the file from the explorer. (Reveral in files)
