### ISSUE TITLE
✨ Add "Duplicate" file command

### ISSUE THREAD

**Issue by Amzoobalance** [ordo-pink/ordo-electron#84]
The `Duplicate` command should be available via:

- [ ] Right click menu on files

If there is a file opened in the Editor, these should work on the currently opened file. It should do nothing if no file is currently opened.

- [ ] Keyboard shortcut (Shift (Cmd on Mac) + Alt + D)

**Comment by orlowdev** [comment]
Oh, forgot one comment here: it should only appear if the file has `.ism` file extension

**Comment by Tayler89Derden** [comment]
Long delay when creating a copy. MacBook pro 2017 MacOs Ventura 13.0

https://user-images.githubusercontent.com/112657403/202439495-e15186f9-d8f5-4fe7-ac3d-adaeeaf64595.mp4
